
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.1:3306/hmhw?autoReconnect=true&useUnicode=true&characterEncoding=utf-8

mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null' #注意：单引号
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    logic-delete-value: 0 # 逻辑已删除值(默认为 1)
    logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #逻辑删除配置

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.weibo.project.app.hmhw.model

logging:
  level:
    com:
      weibo:
        project:
          hmhwservice:
            mapper: debug
